### ISSUE TITLE
Cloud foundry manifest file missing

### ISSUE THREAD

**Issue by upkarlidder** [IBM/python-flask-app#85]
Steps
1. create a new flask application from starter kit
2. the app tells the user to get the source code from `https://github.com/IBM/python-flask-app` The user can download the zip.
3. the zip is missing the `manifest.yaml` file, however the deployment toolchain puts it back when it clones the directory to gitlab.

This is very confusing for a new user. I suggest adding the manifest file here for cloud foundry. It is simply ignored if the user decides to deploy to Kubernetes or Code Engine. Happy to create a PR.

@stevemar 

ps: I think the file used to be here and maybe removed intentionally recently?

**Comment by youming-lin** [comment]
We made a conscious effort back in 2019 to reduce the amount of deployment assets unrelated to the target deployment type; removing the `manifest.yml` was a decision resulting from that.

While I see the reasons for putting it back in, it's not something we are doing right now. We might revisit this in the future though.

**Comment by youming-lin** [comment]
Unfortunately, right now the starter kits are not exactly what-you-see-is-what-you-get; due to the existing architecture, our backend inject some files when these starter kits are deployed to IBM Cloud through our flow. We've made some updates to reduce the amount of generation, so even this today is better than what it was before, when even source code files get modified (now we just inject deploy assets, like charts for Kube, manifest for CF, etc, and miscellaneous assets for CLI and service credentials.). `manifest.yml` in particular would be modified by our generator to have the correct application name, route/domain, and memory selected.

Can it be better? Absolutely. But we haven't settled on what that "better" is, so we are keeping the current format for now.
